### ISSUE TITLE
Relation of this repo to flux-capacitor

### ISSUE THREAD

**Issue by memoriesadrift** [fluxprotocol/flux-index-node#2]
Hi!
I've come across this repo after some digging and wanted to ask how it relates to [flux-capacitor](https://github.com/fluxprotocol/flux-capacitor), since both of them seem to be indexers for NEAR. Is this repo deprecated? Does it serve a different purpose? I can't immediately tell so I'd be grateful for some clarification.
Cheers!

**Comment by jasperdg** [comment]
Hi,

Samuel, this repo is depricated! Thanks for the heads up I'll archive it.
